import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex justify-center items-center h-[calc(100vh-126px)] text-4xl text-blue gill-medium">
        Sign Up
      </div>
    </div>
  );
}
